# --------------
# Band pass filtering
# --------------
Delta: &Delta
  low:
    mean: 0.5
    std: 0.0
  high:
    mean: 4
    std: 0.0
Theta: &Theta
  low:
    mean : 4
    std: 0.0
  high:
    mean: 8
    std: 0.0
Alpha: &Alpha
  low:
    mean: 8
    std: 0.0
  high:
    mean: 12
    std: 0.0
Beta: &Beta
  low:
    mean: 12
    std: 0.0
  high:
    mean: 30
    std: 0.0
Gamma: &Gamma
  low:
    mean: 30
    std: 0.0
  high:
    mean: 45
    std: 0.0
All: &All
  low:
    mean: 0.5
    std: 0.0
  high:
    mean: 45
    std: 0.0

BandPass:
  - name: delta
    <<: *Delta
  - name: theta
    <<: *Theta
  - name: alpha
    <<: *Alpha
  - name: beta
    <<: *Beta
  - name: gamma
    <<: *Gamma
  - name: all
    <<: *All

# --------------
# Other general hyperparameters
# --------------
sampling_freq_high_freq_multiple:  # Sampling freq will be this variable * h_freq
  low: 2
  high: 8
num_seconds:
  low: 5
  high: 60
time_series_start: 30  # This variable should have unit [seconds]
avg_reference: true
remove_above_std:
  low: 20.0e-06
  high: 160.0e-06
interpolation: [ spline, MNE ]

# --------------
# Dataset specific hyperparameters  todo: notch filter?
# --------------
Datasets:
  HatlestadHall:
    session: "t1"
    derivatives: true
  MPILemon:
    interpolation_method: "MNE"
  YulinWang:
    visit: 1
    recording: EC
    derivatives: true
  Miltiadous:
    derivatives: true
