frequency_bands:
  - [ 0.5, 4 ]
  - [ 4, 8 ]
  - [ 8, 12 ]
  - [ 12, 30 ]
  - [ 30, 45 ]
resample_fmax_multiples: [ 2, 4, 8 ]
Datasets:
  HatlestadHall:
    session: "t1"
    derivatives: true
  MPILemon:
    interpolation_method: MNE
    derivatives: false
  YulinWang:
    visit: 1
    recording: EC
    derivatives: true
  Miltiadous:
    derivatives: true
general:
  notch_filter: null
  excluded_channels: null
  main_band_pass: [1, 45]
  num_epochs: 5
  epoch_duration: 5
  epoch_overlap: 0
  time_series_start_secs: 30
  autoreject_resample: 180  # todo
  subject_ids: null