DL Architecture:
  kwargs:
    first_filter_length: 7
    n_layers_per_block: 4
    num_classes: 1
    num_time_steps: 2500
  model: EEGResNetMTS
Training:
  Data Split:
    kwargs:
      seed: 42
    name: SplitOnDataset
  Datasets:
    cau_eeg:
      num_subjects: 150
      num_time_steps: 2500
      time_series_start: null
    hatlestad_hall:
      num_subjects: 111
      num_time_steps: 2500
      time_series_start: null
    miltiadous:
      num_subjects: 88
      num_time_steps: 2500
      time_series_start: null
    ous:
      num_subjects: 20
      num_time_steps: 2500
      time_series_start: null
    rockhill:
      num_subjects: 31
      num_time_steps: 2500
      time_series_start: null
    yulin_wang:
      num_subjects: 60
      num_time_steps: 2500
      time_series_start: null
  Scalers:
    target:
      kwargs: {}
      name: ZNormalisation
  batch_size: 16
  learning_rate: 0.005
  loss: MSELoss
  metrics: regression
  num_epochs: 50
  target: age
  val_split: 0.2
  verbose: true
Varied Numbers of Channels:
  RegionBasedPooling:
    RBPDesigns:
      RBPDesign0:
        num_designs: 1
        pooling_methods: MultiMSSharedRocketHeadRegion
        pooling_methods_kwargs:
          bias: false
          latent_search_features: 32
          max_receptive_field: 100
          num_kernels: 5000
          share_search_receiver_modules: false
        pooling_type: multi_cs
        split_methods:
        - CentroidPolygons
        split_methods_kwargs:
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          min_nodes: 2
      RBPDesign1:
        num_designs: 1
        pooling_methods: MultiMSSharedRocketHeadRegion
        pooling_methods_kwargs:
          bias: false
          latent_search_features: 16
          max_receptive_field: 250
          num_kernels: 500
          share_search_receiver_modules: false
        pooling_type: multi_cs
        split_methods:
        - CentroidPolygons
        - CentroidPolygons
        split_methods_kwargs:
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 2
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          min_nodes: 4
      RBPDesign2:
        num_designs: 1
        pooling_methods: MultiMSSharedRocketHeadRegion
        pooling_methods_kwargs:
          bias: false
          latent_search_features: 64
          max_receptive_field: 75
          num_kernels: 1000
          share_search_receiver_modules: true
        pooling_type: multi_cs
        split_methods:
        - VoronoiSplit
        split_methods_kwargs:
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
      RBPDesign3:
        num_designs: 1
        pooling_methods: MultiMSSharedRocketHeadRegion
        pooling_methods_kwargs:
          bias: false
          latent_search_features: 16
          max_receptive_field: 250
          num_kernels: 250
          share_search_receiver_modules: false
        pooling_type: multi_cs
        split_methods:
        - VoronoiSplit
        split_methods_kwargs:
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
      RBPDesign4:
        num_designs: 1
        pooling_methods: MultiCSSharedRocket
        pooling_methods_kwargs:
          max_receptive_field: 250
          num_kernels: 5000
        pooling_type: multi_cs
        split_methods:
        - VoronoiSplit
        split_methods_kwargs:
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
      RBPDesign5:
        num_designs: 1
        pooling_methods: MultiCSSharedRocket
        pooling_methods_kwargs:
          max_receptive_field: 75
          num_kernels: 500
        pooling_type: multi_cs
        split_methods:
        - CentroidPolygons
        - VoronoiSplit
        split_methods_kwargs:
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 2
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
      RBPDesign6:
        num_designs: 1
        pooling_methods: MultiMSSharedRocketHeadRegion
        pooling_methods_kwargs:
          bias: false
          latent_search_features: 16
          max_receptive_field: 250
          num_kernels: 500
          share_search_receiver_modules: true
        pooling_type: multi_cs
        split_methods:
        - CentroidPolygons
        split_methods_kwargs:
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          min_nodes: 3
      RBPDesign7:
        num_designs: 1
        pooling_methods: MultiMSSharedRocketHeadRegion
        pooling_methods_kwargs:
          bias: false
          latent_search_features: 16
          max_receptive_field: 75
          num_kernels: 1000
          share_search_receiver_modules: false
        pooling_type: multi_cs
        split_methods:
        - CentroidPolygons
        split_methods_kwargs:
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 5
      RBPDesign8:
        num_designs: 1
        pooling_methods: MultiMSSharedRocketHeadRegion
        pooling_methods_kwargs:
          bias: false
          latent_search_features: 16
          max_receptive_field: 100
          num_kernels: 1000
          share_search_receiver_modules: true
        pooling_type: multi_cs
        split_methods:
        - CentroidPolygons
        split_methods_kwargs:
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          min_nodes: 2
    normalise_region_representations: false
