DL Architecture:
  kwargs:
    cnn_units: 32
    depth: 15
    num_classes: 1
  model: InceptionNetwork
DomainDiscriminator: null
Training:
  Data Split:
    kwargs:
      seed: 42
    name: SplitOnDataset
  Datasets:
    cau_eeg:
      num_subjects: 1379
      num_time_steps: 2500
      time_series_start: null
    hatlestad_hall:
      num_subjects: 111
      num_time_steps: 2500
      time_series_start: null
    miltiadous:
      num_subjects: 88
      num_time_steps: 2500
      time_series_start: null
    rockhill:
      num_subjects: 31
      num_time_steps: 2500
      time_series_start: null
    yulin_wang:
      num_subjects: 60
      num_time_steps: 2500
      time_series_start: null
  Scalers:
    target:
      kwargs: {}
      name: ZNormalisation
  batch_size: 16
  learning_rate: 1.0e-04
  eps: 1.0e-08
  beta_1: 0.9
  beta_2: 0.999
  loss: MSELoss
  main_metric: mae
  metrics: regression
  num_epochs: 1000
  target: age
  val_split: 0.2
  verbose: true
Varied Numbers of Channels:
  RegionBasedPooling:
    RBPDesigns:
      RBPDesign0:
        num_designs: 1
        pooling_methods: MultiMSSharedRocketHeadRegion
        pooling_methods_kwargs:
          bias: false
          latent_search_features: 32
          max_receptive_field: 100
          num_kernels: 250
          share_search_receiver_modules: true
        pooling_type: multi_cs
        split_methods:
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        - CentroidPolygons
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        - CentroidPolygons
        - CentroidPolygons
        - CentroidPolygons
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        - CentroidPolygons
        - CentroidPolygons
        - VoronoiSplit
        - CentroidPolygons
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        - CentroidPolygons
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        - CentroidPolygons
        - CentroidPolygons
        - CentroidPolygons
        - CentroidPolygons
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        split_methods_kwargs:
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          min_nodes: 3
        - channel_positions:
          - cau_eeg
          k:
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          min_nodes: 1
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          min_nodes: 4
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 5
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          min_nodes: 2
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 3
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          min_nodes: 1
        - channel_positions:
          - cau_eeg
          k:
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          min_nodes: 4
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          min_nodes: 5
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          min_nodes: 5
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 3
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          min_nodes: 2
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 5
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 5
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          min_nodes: 1
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          min_nodes: 5
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          min_nodes: 1
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
    normalise_region_representations: false
