DL Architecture:
  kwargs:
    n_filters_spat: 25
    n_filters_time: 35
    num_classes: 1
    num_time_steps: 5000
  model: ShallowFBCSPNetMTS
Training:
  Data Split:
    kwargs:
      seed: 42
    name: SplitOnDataset
  Datasets:
    cau_eeg:
      num_subjects: 15
      num_time_steps: 5000
      time_series_start: null
    hatlestad_hall:
      num_subjects: 15
      num_time_steps: 5000
      time_series_start: null
    miltiadous:
      num_subjects: 15
      num_time_steps: 5000
      time_series_start: null
    ous:
      num_subjects: 15
      num_time_steps: 5000
      time_series_start: null
    rockhill:
      num_subjects: 15
      num_time_steps: 5000
      time_series_start: null
    yulin_wang:
      num_subjects: 15
      num_time_steps: 5000
      time_series_start: null
  Scalers:
    target:
      kwargs: {}
      name: ZNormalisation
  batch_size: 16
  learning_rate: 0.005
  loss: L1Loss
  num_epochs: 200
  val_split: 0.2
  verbose: true
Varied Numbers of Channels:
  SphericalSplineInterpolation: YulinWang
