DL Architecture:
  kwargs:
    kernel_length: 64
    num_classes: 1
    num_time_steps: 5000
  model: EEGNetv4MTS
Training:
  Data Split:
    kwargs:
      seed: 42
    name: SplitOnDataset
  Datasets:
    cau_eeg:
      num_subjects: 15
      num_time_steps: 5000
      time_series_start: null
    hatlestad_hall:
      num_subjects: 15
      num_time_steps: 5000
      time_series_start: null
    miltiadous:
      num_subjects: 15
      num_time_steps: 5000
      time_series_start: null
    ous:
      num_subjects: 15
      num_time_steps: 5000
      time_series_start: null
    rockhill:
      num_subjects: 15
      num_time_steps: 5000
      time_series_start: null
    yulin_wang:
      num_subjects: 15
      num_time_steps: 5000
      time_series_start: null
  Scalers:
    target:
      kwargs: {}
      name: ZNormalisation
  batch_size: 16
  learning_rate: 0.0001
  loss: MSELoss
  metrics: regression
  num_epochs: 200
  target: age
  val_split: 0.2
  verbose: true
Varied Numbers of Channels:
  RegionBasedPooling:
    RBPDesigns:
      RBPDesign0:
        num_designs: 1
        pooling_methods: MultiCSSharedRocket
        pooling_methods_kwargs:
          max_receptive_field: 100
          num_kernels: 500
        pooling_type: multi_cs
        split_methods:
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        - CentroidPolygons
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        split_methods_kwargs:
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          min_nodes: 3
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          min_nodes: 1
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          min_nodes: 2
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 1
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
      RBPDesign1:
        num_designs: 1
        pooling_methods: MultiMSSharedRocketHeadRegion
        pooling_methods_kwargs:
          latent_search_features: 32
          max_receptive_field: 100
          num_kernels: 5000
          share_search_receiver_modules: true
        pooling_type: multi_cs
        split_methods:
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        split_methods_kwargs:
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          min_nodes: 2
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 3
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 2
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 4
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
      RBPDesign2:
        num_designs: 1
        pooling_methods: MultiMSSharedRocketHeadRegion
        pooling_methods_kwargs:
          latent_search_features: 16
          max_receptive_field: 250
          num_kernels: 500
          share_search_receiver_modules: true
        pooling_type: multi_cs
        split_methods:
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        - VoronoiSplit
        split_methods_kwargs:
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 4
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          - 3
          - 2
          min_nodes: 2
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 1
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 100
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions:
          - cau_eeg
          k:
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 1
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 500
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems:
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          min_nodes: 1
          num_initial_centroids: 250
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
    normalise_region_representations: true
