preprocessed_version: &preprocessed_version debug_preprocessed_2024-03-07_141650
colormap: viridis
DL Architecture:
  kwargs:
    cnn_units: 128
    depth: 6
    num_classes: 1
  model: InceptionNetwork
Datasets:
  hatlestad_hall:
    num_subjects: 111
    num_time_steps: null
    time_series_start: null
    pre_processed_version: *preprocessed_version
  mpi_lemon:
    num_subjects: 203
    num_time_steps: null
    time_series_start: null
    pre_processed_version: *preprocessed_version
  rockhill:
    num_subjects: 31
    num_time_steps: null
    time_series_start: null
    pre_processed_version: *preprocessed_version
  yulin_wang:
    num_subjects: 60
    num_time_steps: null
    time_series_start: null
    pre_processed_version: *preprocessed_version
  miltiadous:
    num_subjects: 88
    num_time_steps: null
    time_series_start: null
    pre_processed_version: *preprocessed_version
Varied Numbers of Channels:
  RegionBasedPooling:
    RBPDesigns:
      RBPDesign0:
        cmmn_kwargs: null
        num_designs: 1
        pooling_methods: MultiCSSharedRocket
        pooling_methods_kwargs:
          max_receptive_field: 280
          num_kernels: 365
        pooling_type: multi_cs
        split_methods:
        - CentroidPolygons
        - VoronoiSplit
        - CentroidPolygons
        - CentroidPolygons
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        - VoronoiSplit
        - CentroidPolygons
        - VoronoiSplit
        - CentroidPolygons
        - CentroidPolygons
        - VoronoiSplit
        split_methods_kwargs:
        - channel_positions: &id001
          - cau_eeg
          k:
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          - 3
          min_nodes: 4
        - channel_systems: &id003
          - rockhill
          - miltiadous
          - hatlestad_hall
          - yulin_wang
          - cau_eeg
          - mpi_lemon
          min_nodes: 1
          num_initial_centroids: 888
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions: *id001
          k: &id002
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 2
        - channel_positions: *id001
          k: *id002
          min_nodes: 2
        - channel_systems: *id003
          min_nodes: 1
          num_initial_centroids: 353
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions: *id001
          k: &id004
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          min_nodes: 4
        - channel_systems: *id003
          min_nodes: 1
          num_initial_centroids: 232
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_systems: *id003
          min_nodes: 1
          num_initial_centroids: 701
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions: *id001
          k: *id004
          min_nodes: 4
        - channel_systems: *id003
          min_nodes: 1
          num_initial_centroids: 683
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        - channel_positions: *id001
          k: *id004
          min_nodes: 5
        - channel_positions: *id001
          k: *id004
          min_nodes: 4
        - channel_systems: *id003
          min_nodes: 1
          num_initial_centroids: 357
          x_max: 0.17
          x_min: -0.17
          y_max: 0.17
          y_min: -0.17
        use_cmmn_layer: false
    normalise_region_representations: true

# ---------------
# Should not be needed in the future
# ---------------
Training:
  Loss:
    loss: BCEWithLogitsLoss
    loss_kwargs:
      reduction: mean
    weighter: null
    weighter_kwargs:
      weight_power: 0.03802058871731773
  batch_size: 16
  beta_1: 0.875340269168829
  beta_2: 0.9218239786198874
  continuous_testing: true
  eps: 3.4866678043656016e-09
  learning_rate: 1.5038989728172059e-05
  main_metric: auc
  metrics: classification
  num_epochs: 100
  prediction_activation_function: sigmoid
  target: sex
  val_split: 0.2
  verbose: true
DomainDiscriminator: null
